customResourceState:
  enabled: true
  config:
    kind: CustomResourceStateMetrics
    spec:
      resources:
        - groupVersionKind:
            group: jobset.x-k8s.io
            kind: "JobSet"
            version: "v1alpha2"
          labelsFromPath:
            name: [metadata, name]
            uid: [metadata, uid]
            # TODO: Add JobSet labels here that matter.
            some-custom-label: [metadata, labels, some-custom-jobset-label-key]
            # TODO: Add node selector labels here that matter.
            # These labels should be the same across all replicatedJobs
            # in the JobSet so it should be assume index 0 applies for all.
            tpu_accelerator: [spec, replicatedJobs, 0, template, spec, template, spec, nodeSelector, cloud.google.com/gke-tpu-accelerator]
            tpu_topology: [spec, replicatedJobs, 0, template, spec, template, spec, nodeSelector, cloud.google.com/gke-tpu-topology]
            # TODO: Consider how to get "spot" field...
            # it is possible that the field might be different on different
            # replicatedJobs.
            #spot: [spec, replicatedJobs, 0, template, spec, template, spec, nodeSelector, cloud.google.com/gke-spot]
          metrics:
            - name: "jobset_specified_replicas"
              help: "Total number of jobs in the jobset"
              each:
                type: Gauge
                gauge:
                  path: [spec, replicatedJobs]
                  labelsFromPath:
                    replicated_job_name: [name]
                  valueFrom: [replicas]
            - name: "jobset_ready_replicas"
              help: "Total number of jobs in a ready state for the jobset"
              each:
                type: Gauge
                gauge:
                  path: [status, replicatedJobsStatus]
                  labelsFromPath:
                    replicated_job_name: [name]
                  valueFrom: [ready]
            - name: "jobset_restarts"
              help: "Total number of times the JobSet has restarted"
              each:
                type: Gauge
                gauge:
                  path: [status, restarts]
rbac:
  create: true
  useClusterRole: true
  extraRules:
  - apiGroups: ["jobset.x-k8s.io"]
    resources: ["jobsets"]
    verbs: ["list", "watch"]

# Do not collect metrics for most standard resources (to avoid overloading k8s control plane).
collectors: [jobs]

resources:
  # TODO: Modify the CPU and memory limits as needed!!!
  limits:
   cpu: 100m
   memory: 64Mi
  requests:
   cpu: 10m
   memory: 32Mi